tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/drivers"
tap "caskroom/cask"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pcre"
brew "glib"
brew "pixman"
brew "cairo"
brew "pkg-config"
brew "curl"
brew "libksba"
brew "pth"
brew "dirmngr", link: true
brew "dtrx"
brew "emacs", args: ["with-cocoa"], restart_service: true
brew "ffmpeg"
brew "webp"
brew "gd"
brew "gdbm"
brew "gsasl"
brew "icu4c"
brew "libmagic"
brew "libquvi"
brew "readline"
brew "sqlite"
brew "pygtk"
brew "quvi"
brew "xdot"
brew "git-annex"
brew "libtasn1"
brew "nettle"
brew "gnupg", link: false
brew "gpg-agent", link: true
brew "libtool"
brew "graphviz"
brew "irssi"
brew "libidn"
brew "libusb-compat"
brew "lua"
brew "mas"
brew "tokyo-cabinet"
brew "mutt"
brew "pandoc"
brew "remind"
brew "shared-mime-info"
brew "wget"
cask "evernote"
cask "keybase"
cask "mactex"
cask "slack"
cask "steam"
cask "torbrowser"
cask "transmission"
cask "vlc"
cask "caskroom/drivers/sonos"
mas "1Blocker", id: 1107421413
mas "Fantastical 2", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tweetbot", id: 557168941
mas "Twitter", id: 409789998
